runner:
  dotenv-linter:
    cmd: './bin/dotenv-linter'

  golangci-lint:
    cmd: "./bin/golangci-lint run --out-format=line-number --enable-all ./..."

  golint:
    cmd: 'golint ./...'

  govet:
    cmd: 'go vet ./...'
