version: '3.9'
services:

  app:
    build: .
    container_name: app
    image: app
    env_file:
      - ./.env/app.env
    ports:
      - 8081:8081 # K8s probe
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - ./.env/db.env
    ports:
      - 5432:5432

volumes:
  pg-data: