version: 2.1

parameters:
  service_name:
    type: string
    default: "go-service-template"
  image:
    type: string
    default: "evrone/go-clean-template"

orbs:
  docker: circleci/docker@0.5.20

executors:
  default:
    docker:
      - image: circleci/golang:1.16

aliases:
  - &restore-mod-cache
    keys:
      - go-modules-v1-{{ checksum "go.sum" }}
      - go-modules-v1-

  - &save-mod-cache
    key: go-modules-v1-{{ checksum "go.sum" }}
    paths:
      - "/go/pkg/mod"

jobs:
  tests:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache: *restore-mod-cache
      - run:
          name: Tests
          command: go test -v -race ./internal/...
      - save_cache: *save-mod-cache

  integration-tests:
    executor:
      name: default
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Integration tests
          command: docker-compose up --build --abort-on-container-exit --exit-code-from integration

workflows:
  ci:
    jobs:
      - tests
      - integration-tests
